import { Navbar } from "@/components/Navbar/Navbar";
import { Box, ThemeProvider } from "@mui/material";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import theme from "../theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AppRouterCacheProvider options={{ enableCssLayer: true }}>
                    <ThemeProvider theme={theme}>
                        <div>
                            <Navbar></Navbar>
                            <Box
                                component={"main"}
                                sx={{
                                    flexGrow: 1,
                                    bgcolor: "backgroud.default",
                                    mt: ["122px", "135px", "146px"],
                                    p: 3,
                                }}
                            >
                                {children}
                            </Box>
                        </div>
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
